<?php

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */

/** @var \Twint\MagentoHyva\Magewire\Payment\Method\ExpressButton $magewire */
$magewire = $block->getMagewire();

$uniqueId = uniqid();

?>

<div x-data="expressCheckout_<?= $uniqueId ?>">
    <?php if ($magewire->shouldRender()): ?>
    <?= $block->getLayout()
              ->createBlock(\Magento\Framework\View\Element\Template::class, 'twint.express-button' . $uniqueId)
              ->setTemplate('Twint_MagentoHyva::checkout/express-checkout/button.phtml')
              ->toHtml() ?>

    <script>
        "use strict";

        function expressCheckout_<?= $uniqueId ?>() {
            return Object.assign(
                {
                    isLoading: false,
                    checkout() {
                        window.dispatchEvent(new CustomEvent("twint-start-loading"));
                        let postData = {
                            whole_cart: 1,
                            form_key: hyva.getFormKey(),
                        };

                        const expressCheckoutUrl = '<?= $block->getUrl('twint/express/checkout') ?>';
                        const expressCheckoutPayload = {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
                            },
                            body: new URLSearchParams(postData).toString()
                        };

                        fetch(expressCheckoutUrl, expressCheckoutPayload)
                            .then(resp => resp.json())
                            .then(response => {
                                window.dispatchEvent(new CustomEvent('twint-modal-open', {detail: {response}}));
                                window.dispatchEvent(new CustomEvent('twint-stop-loading'));
                            });
                    },
                }
            )
        }

        window.addEventListener(
            'alpine:init',
            () => Alpine.data('expressCheckout_<?= $uniqueId ?>', expressCheckout_<?= $uniqueId ?>),
            {once: true}
        )
    </script>

    <?php $hyvaCsp->registerInlineScript(); ?>

    <?php endif; ?>
</div>
