<?php

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */

/** @var \Twint\MagentoHyva\Magewire\Payment\Method\ExpressButton $magewire */
$magewire = $block->getMagewire();

$uniqueId = uniqid();

?>

<div x-data="expressCheckout_<?= $uniqueId ?>" class="ml-2 tw-button-wrapper pdp">
    <?php if ($magewire->shouldRender()): ?>

    <?= $block->getLayout()
              ->createBlock(\Magento\Framework\View\Element\Template::class, 'twint.express-button' . $uniqueId)
              ->setTemplate('Twint_MagentoHyva::checkout/express-checkout/button.phtml')
              ->toHtml() ?>

    <script>
        "use strict";

        function expressCheckout_<?= $uniqueId ?>() {
            return Object.assign(
                {
                    checkout() {
                        const form = document.getElementById('product_addtocart_form');

                        if (!form.reportValidity()) {
                            return;
                        }

                        window.dispatchEvent(new CustomEvent("twint-start-loading"));
                        let postData = {};

                        Array.from(form.querySelectorAll(
                            '[name^=product], [name^=selected_configurable_options], [name^=related_product], [name^=item], [name^=form_key], [name^=options], [name^=super_attribute], [name^=bundle_option], [name^=super_group], [name^=links]')
                        ).map(input => {
                            if (input.type === "select-multiple") {
                                Array.from(input.selectedOptions).forEach(option => {
                                    postData.push(`${input.name}[]=${option.value}`)
                                })
                            } else {
                                // skip "checkable inputs" that are not checked
                                if (!(['radio', 'checkbox', 'select'].includes(input.type) && !input.checked)) {
                                    postData[input.name] = input.value;
                                }
                            }
                        });

                        postData.qty = document.getElementById('qty[' + postData.product + ']')?.value;

                        const expressCheckoutUrl = '<?= $block->getUrl('twint/express/checkout') ?>';
                        const expressCheckoutPayload = {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
                            },
                            body: new URLSearchParams(postData).toString()
                        };

                        fetch(expressCheckoutUrl, expressCheckoutPayload)
                            .then(resp => resp.json())
                            .then(response => {
                                window.dispatchEvent(new CustomEvent('twint-modal-open', {detail: {response}}));
                                window.dispatchEvent(new CustomEvent('twint-stop-loading'));
                            });
                    },
                }
            )
        }

        window.addEventListener(
            'alpine:init',
            () => Alpine.data('expressCheckout_<?= $uniqueId ?>', expressCheckout_<?= $uniqueId ?>),
            {once: true}
        )
    </script>

    <?php $hyvaCsp->registerInlineScript(); ?>

    <?php endif; ?>
</div>
