<?php

declare(strict_types=1);

/**
 * @var \Hyva\TwintPayment\Magewire\Payment\Method\TwintRegular $magewire
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<div class="twint">
    <script>
        (function () {
            // Ensure that the evaluation API is fully initialized.
            window.addEventListener('checkout:init:evaluation', () => {
                // Open a modal after 5 seconds, including fetched data from an external API.
                hyvaCheckout.evaluation.registerExecutable('custom-modal', async (result, el, component) => {
                    console.log('result', result.arguments.params);
                })
            })
        })();
    </script>
</div>

